### PR TITLE
Deploy to npm on tagged releases

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
I didn't have it deploy on merges to master but instead made it release on tags so that PRs to be merged to master don't have to bump versions as a part of it.

### CODE REVIEW

**Comment by taras** [comment]
What's the process for using this?

**Comment by sivakumar-kailasam** [comment]
whenever a new git tag is created and pushed to this repo, it'll deploy to npm.

**Comment by sivakumar-kailasam** [comment]
@taras @cowboyd How about using https://github.com/semantic-release/semantic-release?

**Comment by taras** [comment]
@sivakumar-kailasam it looks good, whats the difference between that and `standard-version`?

**Comment by cowboyd** [comment]
We're going to use the new github actions for this.

**Pull request closed without merging**
