### PR TITLE
Added coverage reporting

### PR DESCRIPTION
**Pull request by taras**
# Purpose
Instead of removing coverage in #247, we can fix our coverage report to show the real value.

[Coverage Status](https://coveralls.io/github/microstates/microstates.js?branch=tm%2Fsetup-coverage)

# Approach

Adding Istanbul, `nyc` and configure to generate a test coverage report when `npm test` command is executed. I configured travis to push the coverage report to coveralls after tests pass successfully.

### CODE REVIEW

**Comment by cowboyd** [comment]
Only 89%? 🤔 What's in the coverage report that shows up as missing?

**Comment by taras** [comment]
image

https://coveralls.io/github/microstates/microstates.js?branch=tm%2Fsetup-coverage

**Comment by cowboyd** [comment]
Can we ignore the `test/` director?

**Comment by taras** [comment]
@cowboyd I excluded it, it made very little difference. There looks to be some low hanging fruit to fix the coverage.

**Pull request merged**
