### PR TITLE
Transparent Publishing for Microstates.js

### PR DESCRIPTION
**Pull request by minkimcello**
# Purpose
This PR is to setup Transparent NPM Publishing **(w/ Github Actions)**. There are a few steps that must be taken before merging this PR. **Please refer to the Setup section below.**

# Approach
NEW_DIAGRAM

_* currently set to `master` but concurrent release filtering works properly and has been commented out so see `.github/workflows/pr-create.yml` and `.github/workflows/pr-merge.yml` to make the necessary changes._

## When PR is created
The changes in the pull request will publish to NPM (if it passes all the tests) and post a comment to inform that the code in this PR is available as an NPM package.

## When PR is merged
The tests will run again and if they all pass, TNP will increment the version based on the labels of the merged PR, push package.json back to the repo, and then publish to NPM.

# Setup Checklist
Below are the steps necessary to integrate TNP to Microstates.js:
- [ ] 1. Add the following to the `secrets` in the repository settings:
    - [ ] `NPM_AUTH_TOKEN`: from npmjs.
    - [ ] `GITHUB_TOKEN`: personal access token from the Microstates' Github.
    - [ ] `DANGER_GITHUB`: personal access token from Github bot account (public repo permission)
    - [ ] Optional: `SEMVER_USER_NAME` & `SEMVER_USER_EMAIL`

- [ ] 2. Fix coveralls in tests. (Temporarily commented out coveralls so that the rest of the job can proceed.)

- [ ] 3. Currently `pr-create.yml`/`pr-merge.yml` workflows are set for the `master` branch. Concurrent release works properly so uncomment `release-*` and comment out `master` once ready.

# Learning
This setup has been adapted from [Georgia](https://github.com/taras/georgia/tree/release-1.0.0).

### CODE REVIEW

**Comment by cowboyd** [comment]
@minkimcello What service accounts and tokens do we need added to the Environment for this to work?

**Comment by minkimcello** [comment]
> @minkimcello What service accounts and tokens do we need added to the Environment for this to work?

Personal access tokens from the Microstates' Github account and from one of your Github bot accounts, token from npmjs.com, and User SSH key from CircleCI. 

I've outlined the necessary steps in the Steps section above in the PR body.

**Comment by cowboyd** [comment]
Thanks! Can you add these to the checklist?

**Comment by minkimcello** [comment]
> Thanks! Can you add these to the checklist?

updated checklist in the PR

**Pull request closed without merging**
