### PR TITLE
Convert microstates into a monorepo

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation
We're going to consolidate the repositories of the microstates org into this monorepo and transfer ownership to @thefrontside.

## Approach
- Copied all the contents of this repository and put it into `packages/microstates/` (minus the `.js`).
- Added `lerna.json`, `package.json`, and `.gitignore`.
- Note: Didn't need to use `lerna` to import because all the commit history is already here.
- Maintaining CircleCI setup for `test`, `lint`, `coverage`, and `coveralls` but not yet running in a matrix. We will modify as we go or possibly move over to Github Actions to keep all checks on one platform.

### CODE REVIEW

**Comment by cowboyd** [comment]
Is the plan to use learn and not yarn workspaces? What's the relative tradeoff?

**Comment by taras** [comment]
> Is the plan to use learn and not yarn workspaces? What's the relative tradeoff?

@minkimcello my idea was to only use lerna for `lerna import`. We shouldn't add it as a dependency unless there are other features that we want to use.

**Comment by frontsidejack** [comment]
A preview package of this pull request has been published with the tag `mk_monorepo-conversion`.
You can try it out by running the following command:
```bash
$ npm install microstates@mk_monorepo-conversion
```
or by updating your package.json to:
```bash
{
  "microstates": "mk_monorepo-conversion"
}
```
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 87e87ce6c86b74520b6a6866f198c286aab05c35
</p>

**Comment by frontsidejack** [comment]
A preview package of this pull request has been published with the tag `mk_monorepo-conversion`.
You can try it out by running the following command:
```bash
$ npm install microstates@mk_monorepo-conversion
```
or by updating your package.json to:
```bash
{
  "microstates": "mk_monorepo-conversion"
}
```
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5e8a88a768ce2b1216a0aaceb9457be522fa9aae
</p>

**Pull request merged**
